import React from "react";
import { Link, useLocation } from "react-router-dom";

export default function InfoPage() {
  const { pathname } = useLocation();
  const page = pathname === "/terms" ? "terms" : pathname === "/privacy" ? "privacy" : "recovery";
  const content = {
    terms: { title: "Terms of Service", intro: "These are starter terms for the CareerHub project and should be reviewed by the service owner before public launch.", sections: [["Use of the service", "Use CareerHub lawfully and provide accurate information in your profile, resume, job applications and saved workspace records."], ["AI-generated content", "AI responses are suggestions. Review and verify generated resumes, cover letters, interview feedback and career guidance before using them. CareerHub does not guarantee an interview, offer or hiring outcome."], ["External services", "Job listings, payment checkout and learning links may be supplied by third-party services. Their availability and terms are controlled by those providers."], ["Account security", "Keep your sign-in credentials private and contact the service owner if you suspect unauthorized account access."]] },
    privacy: { title: "Privacy Policy", intro: "This starter privacy notice describes the intended handling of CareerHub account data. The service owner must review it against the actual deployment and applicable law before launch.", sections: [["Account and workspace data", "CareerHub stores account details and records you choose to save, such as applications, companies, contacts, activities, learning resources and roadmap items."], ["AI and uploaded files", "When you use AI tools, the submitted text or resume is sent to the configured AI provider. Avoid submitting passwords, financial details or other unnecessary sensitive information."], ["Third-party providers", "Job search and payment features may contact configured job providers or Stripe. Those providers process data under their own terms and privacy notices."], ["Retention and contact", "The deployment owner should publish a support contact and a clear process for account deletion, data requests and retention before production launch."]] },
    recovery: { title: "Password recovery", intro: "Password-reset email delivery is not configured in this project yet, so CareerHub cannot safely send a reset link from this screen.", sections: [["What to do next", "Contact your CareerHub administrator to recover account access. Do not share your current password with anyone."], ["For the deployment owner", "Enable a verified email provider, implement expiring one-time reset tokens, and test the reset flow before making this option available to users."]] },
  }[page];
  return <main className="min-h-screen bg-slate-50 px-5 py-12 text-slate-900"><article className="mx-auto max-w-3xl rounded-2xl border bg-white p-6 shadow-sm sm:p-10"><Link to="/" className="text-sm font-semibold text-blue-700">← CareerHub home</Link><h1 className="mt-5 text-3xl font-bold">{content.title}</h1><p className="mt-3 leading-7 text-slate-600">{content.intro}</p><div className="mt-7 space-y-6">{content.sections.map(([heading, body]) => <section key={heading}><h2 className="font-semibold">{heading}</h2><p className="mt-2 leading-7 text-slate-600">{body}</p></section>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/login" className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Sign in</Link><Link to="/signup" className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Create account</Link></div></article></main>;
}
